" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
"syntax on

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
"    \| exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"if has("autocmd")
"  filetype plugin indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes) in terminals

" Source a global configuration file if available
" XXX Deprecated, please move your changes here in /etc/vim/vimrc
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

set nocompatible " Включаем несовместимость настроек с Vi (ибо Vi нам и не понадобится).

syntax enable
colorscheme elflord

" Не выгружать буфер, когда переключаемся на другой
" Это позволяет редактировать несколько файлов в один и тот же момент без необходимости сохранения каждый раз
" когда переключаешься между ними
set hidden

set showcmd " Показывать незавершённые команды в статусбаре
set hlsearch " при поиске помечать все найденные строки
set incsearch " при поиске перескакивать на найденный текст в процессе набора строки
set ignorecase " игнорировать прописные/строчные при поиске
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab " Преобразование Таба в пробелы
set smartindent " Включаем "умные" отспупы ( например, автоотступ после {)
set autoindent " автоотступ

" Включить подсветку для табов, а так же завершающих пробелов
set list
set listchars=tab:>-,trail:-

" При вставке сохранять отступы
set pastetoggle=

" Включить сворачивание/разворачивание кода
set foldenable
let php_folding=1

"set nowrap " не разрывать строку
set sidescroll=5 " прокрутка вправо/влево когда строка заежает за край и вы по ней ползаете

set ruler " Показывать положение курсора всё время.

" Поддержка мыши
"set mouse=a
"set mousemodel=popup

set termencoding=utf-8 " Кодировка текста по умолчанию

set ch=1 " Сделать строку команд высотой в одну строку
set mousehide " Скрывать указатель мыши, когда печатаем

" Формат строки состояния
set statusline=%<%F%h%m%r%h%w%y\ %{&ff}\ %{strftime(\"%d/%m/%Y-%H:%M\")}%=\ col:%c%V\ ascii:%b\ pos:%o\ lin:%l\,%L\ %P
set laststatus=2

" Выключаем ненавистный режим замены
imap >Ins> <Esc>i

map <f2> :w\|!php %
map <f3> :w\|!python %
